### ISSUE TITLE
Missing thumbnails and status:banned

### ISSUE THREAD

**Issue by bluefiberbread** [friendlyanon/decensooru#3]
There are missing thumbnails for the banned tags and the tag "status:banned" won't load either

Did I do something wrong while installing the userscript? Some of the banned tags will load, but a majority of those tags won't load for some reason

**Comment by friendlyanon** [comment]
Yes, the usual URL pattern returns a 404 HTTP code in the case of these newer uploads.
Without a VIP or similar high priviliged API key I cannot investigate further.

**Comment by friendlyanon** [comment]
Nevermind, found the actual cause of the issue. The current solution is a bandaid fix, but I can't be bothered to find the post ID from which the new server `raikou4` is being used.
