### ISSUE TITLE
Newpipe Legacy maintainership

### ISSUE THREAD

**Issue by opusforlife2** [friendlyanon/decensooru#6]
Hey, @friendlyanon. I'm contacting you regarding Newpipe-Legacy, because you're still a part of the team on Github. Newpipe will soon set the minimum API level to 21 (Lollipop), dropping Kitkat support. Are you still interested in updating and maintaining the Legacy version? 

Sorry for the off-topic ping. You're not in the Newpipe IRC channel and so we needed a way to contact you. If you're still interested in developing for the app, please join the channel. If not, please inform us so that we can look for another developer or archive the repo.

Thanks.

**Comment by opusforlife2** [comment]
@friendlyanon Ping.

**Comment by friendlyanon** [comment]
Sorry, I do not care anymore. SponsorBlock (or the lack of its inclusion) is what made me just update my phone, making this irrelevant for me.
